### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by extremeheat** [extremeheat/protodef-cpp#3]
- [ ] C support (this will enable easy embedding into mobile apps with ios swift+c interop)
  - [ ] Explore how to expand to Python/Go for backend
  - [ ] maybe Java for Android without JNI (or a util function to autogen C & Java JNI glue code)
- [ ] JSON encode/decode support
- [ ] Better custom type support so it works better with cross-languages
- [ ] gRPC-like support for network comms
  - existing minecraft bedrock protocol already uses _request and _response suffixes for C<->S comms... maybe use that for simplicity w/o needing syntax changes
- [ ] Look at embedding YAML comments into generated C/C++. This would require protodef-yaml to pass the comments in special syntax to the generated ProtoDef JSON
